CREATE WAREHOUSE CAT_GIT_WHWH WITH 
  WAREHOUSE_SIZE = XSmall 
  INITIALLY_SUSPENDED = true;

USE WAREHOUSE CAT_GIT_WHWH;

CREATE OR REPLACE DATABASE CAT_GIT_week14_db;

USE DATABASE CAT_GIT_week14_db;

CREATE OR REPLACE SCHEMA CAT_GIT_week14_schema;

USE SCHEMA CAT_GIT_week14_schema;
